// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: api/vehicle.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Vehicle struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Plate         string                 `protobuf:"bytes,2,opt,name=plate,proto3" json:"plate,omitempty"`
	Model         string                 `protobuf:"bytes,3,opt,name=model,proto3" json:"model,omitempty"`
	ColdChain     bool                   `protobuf:"varint,4,opt,name=cold_chain,json=coldChain,proto3" json:"cold_chain,omitempty"`
	IceBoxNo      string                 `protobuf:"bytes,5,opt,name=ice_box_no,json=iceBoxNo,proto3" json:"ice_box_no,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Vehicle) Reset() {
	*x = Vehicle{}
	mi := &file_api_vehicle_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Vehicle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vehicle) ProtoMessage() {}

func (x *Vehicle) ProtoReflect() protoreflect.Message {
	mi := &file_api_vehicle_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vehicle.ProtoReflect.Descriptor instead.
func (*Vehicle) Descriptor() ([]byte, []int) {
	return file_api_vehicle_proto_rawDescGZIP(), []int{0}
}

func (x *Vehicle) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Vehicle) GetPlate() string {
	if x != nil {
		return x.Plate
	}
	return ""
}

func (x *Vehicle) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *Vehicle) GetColdChain() bool {
	if x != nil {
		return x.ColdChain
	}
	return false
}

func (x *Vehicle) GetIceBoxNo() string {
	if x != nil {
		return x.IceBoxNo
	}
	return ""
}

type CreateVehicleReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Plate         string                 `protobuf:"bytes,1,opt,name=plate,proto3" json:"plate,omitempty"`
	Model         string                 `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	ColdChain     bool                   `protobuf:"varint,3,opt,name=cold_chain,json=coldChain,proto3" json:"cold_chain,omitempty"`
	IceBoxNo      string                 `protobuf:"bytes,4,opt,name=ice_box_no,json=iceBoxNo,proto3" json:"ice_box_no,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateVehicleReq) Reset() {
	*x = CreateVehicleReq{}
	mi := &file_api_vehicle_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateVehicleReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVehicleReq) ProtoMessage() {}

func (x *CreateVehicleReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_vehicle_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVehicleReq.ProtoReflect.Descriptor instead.
func (*CreateVehicleReq) Descriptor() ([]byte, []int) {
	return file_api_vehicle_proto_rawDescGZIP(), []int{1}
}

func (x *CreateVehicleReq) GetPlate() string {
	if x != nil {
		return x.Plate
	}
	return ""
}

func (x *CreateVehicleReq) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *CreateVehicleReq) GetColdChain() bool {
	if x != nil {
		return x.ColdChain
	}
	return false
}

func (x *CreateVehicleReq) GetIceBoxNo() string {
	if x != nil {
		return x.IceBoxNo
	}
	return ""
}

type UpdateVehicleReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Plate         string                 `protobuf:"bytes,2,opt,name=plate,proto3" json:"plate,omitempty"`
	Model         string                 `protobuf:"bytes,3,opt,name=model,proto3" json:"model,omitempty"`
	ColdChain     bool                   `protobuf:"varint,4,opt,name=cold_chain,json=coldChain,proto3" json:"cold_chain,omitempty"`
	IceBoxNo      string                 `protobuf:"bytes,5,opt,name=ice_box_no,json=iceBoxNo,proto3" json:"ice_box_no,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateVehicleReq) Reset() {
	*x = UpdateVehicleReq{}
	mi := &file_api_vehicle_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateVehicleReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateVehicleReq) ProtoMessage() {}

func (x *UpdateVehicleReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_vehicle_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateVehicleReq.ProtoReflect.Descriptor instead.
func (*UpdateVehicleReq) Descriptor() ([]byte, []int) {
	return file_api_vehicle_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateVehicleReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateVehicleReq) GetPlate() string {
	if x != nil {
		return x.Plate
	}
	return ""
}

func (x *UpdateVehicleReq) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *UpdateVehicleReq) GetColdChain() bool {
	if x != nil {
		return x.ColdChain
	}
	return false
}

func (x *UpdateVehicleReq) GetIceBoxNo() string {
	if x != nil {
		return x.IceBoxNo
	}
	return ""
}

type GetVehicleReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVehicleReq) Reset() {
	*x = GetVehicleReq{}
	mi := &file_api_vehicle_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVehicleReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVehicleReq) ProtoMessage() {}

func (x *GetVehicleReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_vehicle_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVehicleReq.ProtoReflect.Descriptor instead.
func (*GetVehicleReq) Descriptor() ([]byte, []int) {
	return file_api_vehicle_proto_rawDescGZIP(), []int{3}
}

func (x *GetVehicleReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListVehiclesReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Offset        int32                  `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVehiclesReq) Reset() {
	*x = ListVehiclesReq{}
	mi := &file_api_vehicle_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVehiclesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVehiclesReq) ProtoMessage() {}

func (x *ListVehiclesReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_vehicle_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVehiclesReq.ProtoReflect.Descriptor instead.
func (*ListVehiclesReq) Descriptor() ([]byte, []int) {
	return file_api_vehicle_proto_rawDescGZIP(), []int{4}
}

func (x *ListVehiclesReq) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListVehiclesReq) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListVehiclesResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Vehicle             `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVehiclesResp) Reset() {
	*x = ListVehiclesResp{}
	mi := &file_api_vehicle_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVehiclesResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVehiclesResp) ProtoMessage() {}

func (x *ListVehiclesResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_vehicle_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVehiclesResp.ProtoReflect.Descriptor instead.
func (*ListVehiclesResp) Descriptor() ([]byte, []int) {
	return file_api_vehicle_proto_rawDescGZIP(), []int{5}
}

func (x *ListVehiclesResp) GetItems() []*Vehicle {
	if x != nil {
		return x.Items
	}
	return nil
}

type GetUploadURLReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Suffix        string                 `protobuf:"bytes,1,opt,name=suffix,proto3" json:"suffix,omitempty"` // 文件后缀，如 .jpg
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUploadURLReq) Reset() {
	*x = GetUploadURLReq{}
	mi := &file_api_vehicle_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUploadURLReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUploadURLReq) ProtoMessage() {}

func (x *GetUploadURLReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_vehicle_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUploadURLReq.ProtoReflect.Descriptor instead.
func (*GetUploadURLReq) Descriptor() ([]byte, []int) {
	return file_api_vehicle_proto_rawDescGZIP(), []int{6}
}

func (x *GetUploadURLReq) GetSuffix() string {
	if x != nil {
		return x.Suffix
	}
	return ""
}

type GetUploadURLResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UploadUrl     string                 `protobuf:"bytes,1,opt,name=upload_url,json=uploadUrl,proto3" json:"upload_url,omitempty"`
	ObjectKey     string                 `protobuf:"bytes,2,opt,name=object_key,json=objectKey,proto3" json:"object_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUploadURLResp) Reset() {
	*x = GetUploadURLResp{}
	mi := &file_api_vehicle_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUploadURLResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUploadURLResp) ProtoMessage() {}

func (x *GetUploadURLResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_vehicle_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUploadURLResp.ProtoReflect.Descriptor instead.
func (*GetUploadURLResp) Descriptor() ([]byte, []int) {
	return file_api_vehicle_proto_rawDescGZIP(), []int{7}
}

func (x *GetUploadURLResp) GetUploadUrl() string {
	if x != nil {
		return x.UploadUrl
	}
	return ""
}

func (x *GetUploadURLResp) GetObjectKey() string {
	if x != nil {
		return x.ObjectKey
	}
	return ""
}

var File_api_vehicle_proto protoreflect.FileDescriptor

const file_api_vehicle_proto_rawDesc = "" +
	"\n" +
	"\x11api/vehicle.proto\x12\x03api\"\x82\x01\n" +
	"\aVehicle\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05plate\x18\x02 \x01(\tR\x05plate\x12\x14\n" +
	"\x05model\x18\x03 \x01(\tR\x05model\x12\x1d\n" +
	"\n" +
	"cold_chain\x18\x04 \x01(\bR\tcoldChain\x12\x1c\n" +
	"\n" +
	"ice_box_no\x18\x05 \x01(\tR\biceBoxNo\"{\n" +
	"\x10CreateVehicleReq\x12\x14\n" +
	"\x05plate\x18\x01 \x01(\tR\x05plate\x12\x14\n" +
	"\x05model\x18\x02 \x01(\tR\x05model\x12\x1d\n" +
	"\n" +
	"cold_chain\x18\x03 \x01(\bR\tcoldChain\x12\x1c\n" +
	"\n" +
	"ice_box_no\x18\x04 \x01(\tR\biceBoxNo\"\x8b\x01\n" +
	"\x10UpdateVehicleReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05plate\x18\x02 \x01(\tR\x05plate\x12\x14\n" +
	"\x05model\x18\x03 \x01(\tR\x05model\x12\x1d\n" +
	"\n" +
	"cold_chain\x18\x04 \x01(\bR\tcoldChain\x12\x1c\n" +
	"\n" +
	"ice_box_no\x18\x05 \x01(\tR\biceBoxNo\"\x1f\n" +
	"\rGetVehicleReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"?\n" +
	"\x0fListVehiclesReq\x12\x16\n" +
	"\x06offset\x18\x01 \x01(\x05R\x06offset\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"6\n" +
	"\x10ListVehiclesResp\x12\"\n" +
	"\x05items\x18\x01 \x03(\v2\f.api.VehicleR\x05items\")\n" +
	"\x0fGetUploadURLReq\x12\x16\n" +
	"\x06suffix\x18\x01 \x01(\tR\x06suffix\"P\n" +
	"\x10GetUploadURLResp\x12\x1d\n" +
	"\n" +
	"upload_url\x18\x01 \x01(\tR\tuploadUrl\x12\x1d\n" +
	"\n" +
	"object_key\x18\x02 \x01(\tR\tobjectKey2\xa6\x02\n" +
	"\x0eVehicleService\x124\n" +
	"\rCreateVehicle\x12\x15.api.CreateVehicleReq\x1a\f.api.Vehicle\x124\n" +
	"\rUpdateVehicle\x12\x15.api.UpdateVehicleReq\x1a\f.api.Vehicle\x12.\n" +
	"\n" +
	"GetVehicle\x12\x12.api.GetVehicleReq\x1a\f.api.Vehicle\x12;\n" +
	"\fListVehicles\x12\x14.api.ListVehiclesReq\x1a\x15.api.ListVehiclesResp\x12;\n" +
	"\fGetUploadURL\x12\x14.api.GetUploadURLReq\x1a\x15.api.GetUploadURLRespB/Z-github.com/laoggu/cabbage-vehicle-backend/apib\x06proto3"

var (
	file_api_vehicle_proto_rawDescOnce sync.Once
	file_api_vehicle_proto_rawDescData []byte
)

func file_api_vehicle_proto_rawDescGZIP() []byte {
	file_api_vehicle_proto_rawDescOnce.Do(func() {
		file_api_vehicle_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_vehicle_proto_rawDesc), len(file_api_vehicle_proto_rawDesc)))
	})
	return file_api_vehicle_proto_rawDescData
}

var file_api_vehicle_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_api_vehicle_proto_goTypes = []any{
	(*Vehicle)(nil),          // 0: api.Vehicle
	(*CreateVehicleReq)(nil), // 1: api.CreateVehicleReq
	(*UpdateVehicleReq)(nil), // 2: api.UpdateVehicleReq
	(*GetVehicleReq)(nil),    // 3: api.GetVehicleReq
	(*ListVehiclesReq)(nil),  // 4: api.ListVehiclesReq
	(*ListVehiclesResp)(nil), // 5: api.ListVehiclesResp
	(*GetUploadURLReq)(nil),  // 6: api.GetUploadURLReq
	(*GetUploadURLResp)(nil), // 7: api.GetUploadURLResp
}
var file_api_vehicle_proto_depIdxs = []int32{
	0, // 0: api.ListVehiclesResp.items:type_name -> api.Vehicle
	1, // 1: api.VehicleService.CreateVehicle:input_type -> api.CreateVehicleReq
	2, // 2: api.VehicleService.UpdateVehicle:input_type -> api.UpdateVehicleReq
	3, // 3: api.VehicleService.GetVehicle:input_type -> api.GetVehicleReq
	4, // 4: api.VehicleService.ListVehicles:input_type -> api.ListVehiclesReq
	6, // 5: api.VehicleService.GetUploadURL:input_type -> api.GetUploadURLReq
	0, // 6: api.VehicleService.CreateVehicle:output_type -> api.Vehicle
	0, // 7: api.VehicleService.UpdateVehicle:output_type -> api.Vehicle
	0, // 8: api.VehicleService.GetVehicle:output_type -> api.Vehicle
	5, // 9: api.VehicleService.ListVehicles:output_type -> api.ListVehiclesResp
	7, // 10: api.VehicleService.GetUploadURL:output_type -> api.GetUploadURLResp
	6, // [6:11] is the sub-list for method output_type
	1, // [1:6] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_vehicle_proto_init() }
func file_api_vehicle_proto_init() {
	if File_api_vehicle_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_vehicle_proto_rawDesc), len(file_api_vehicle_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_vehicle_proto_goTypes,
		DependencyIndexes: file_api_vehicle_proto_depIdxs,
		MessageInfos:      file_api_vehicle_proto_msgTypes,
	}.Build()
	File_api_vehicle_proto = out.File
	file_api_vehicle_proto_goTypes = nil
	file_api_vehicle_proto_depIdxs = nil
}
